{% set name = "flet-runtime" %}
{% set version = "0.21.2" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet_runtime-{{ version }}.tar.gz
  sha256: 230d2fa758eab77c8e8f517a9c1f390926c30610b348a29b8c211dfcf63376a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0
    - flet-core =={{ version }}
    - oauthlib >=3.2.2,<4.0.0
    - httpx >=0.0.0,<1.0.0

test:
  imports:
    - flet_runtime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet/tree/main/sdk/python/packages/flet-runtime
  summary: Flet Runtime - a base package for Flet desktop and Flet mobile.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
