{% set name = "flet-runtime" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet_runtime-{{ version }}.tar.gz
  sha256: 55f3d37c2257a5166c28ce13a05ca5ef3c5b939f074fa78e62d85fcc03387fcf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7,<4.0
    - flet-core =={{ version }}
    - oauthlib >=3.2.2,<4.0.0
    - httpx >=0.24.1,<0.25.0
    - typing-extensions >=4.6.2,<5.0.0

test:
  imports:
    - flet_runtime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet/tree/main/sdk/python/packages/flet-runtime
  summary: Flet Runtime - a base package for Flet desktop and Flet mobile.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
